cmd/context.go

closes #7 
more translation of other bash completion functions to come.

pure golang based completion for context

---

cmd/printer.go

Show chassis and product serial for metalctl machine ipmi

---

cmd/update.go
docker-make.yml

dump version json to result folder, upload it to GCS and use GCS as download URL

Use GCS for version files and as download source

---

cmd/printer.go

To be able to see in one go, which firewall has been created recently

show age of firewall

---

cmd/context.go

@ulrichSchreiner for your shell prompt

add context short for much easier shell prompt mechanic

---

cmd/helper.go
cmd/network.go
cmd/printer.go
cmd/project.go
go.mod
go.sum

Implements: https://github.com/metal-stack/metal-api/pull/95

show network.labels in metalctl network ls -o wide

---

cmd/machine.go
cmd/printer.go

- Can now show multiple issues per machine
- Dedicated table printer for issues
- Added test for overlapping ASN

Overhaul of machine issues command.

---

go.mod
go.sum

Update cobra to fix zsh completion

---

cmd/machine.go
cmd/printer.go
go.mod
go.sum

fixes https://github.com/metal-stack/metalctl/issues/39
Related:
* https://github.com/metal-stack/metal-core/pull/34
* https://github.com/metal-stack/metal-api/pull/140
* https://github.com/metal-stack/metal-go/pull/51

Extend power cmd

---

cmd/machine.go
cmd/root.go
go.mod
go.sum

Usage:
```
/bin/metalctl machine rm e0ab02d2-27cd-5a5e-8efc-080ba80cf258 --remove-from-database --yes-i-really-mean-it
```

implement machine deletion

---

cmd/health.go
cmd/root.go
cmd/version.go
go.mod
go.sum

Adding health and version commands.

---

cmd/printer.go

show fsl even if wide was specified

---

cmd/filesystemlayout.go
cmd/image.go
cmd/network.go
cmd/partition.go
cmd/project.go
cmd/size.go

#90 changed behavior of apply leading to failures in the integration tests.

Fix for broken apply commands.

---

cmd/helper.go
cmd/machine.go

https://github.com/metal-stack/metal-core/pull/38

Add prompt with explanations on firmware update commands.

---

cmd/printer.go

Add missing wide headers.

---

cmd/completion.go
cmd/filesystemlayout.go
cmd/firewall.go
cmd/image.go
cmd/machine.go
cmd/network.go
cmd/partition.go
cmd/project.go
cmd/size.go
go.mod
go.sum

Add completion for all commands which take the id of the noun as direct argument

More completions

---

cmd/printer.go
cmd/root.go
go.mod
go.sum

Wait for tagged metal-go, then ready to merge

Show powerstate

---

cmd/printer.go

Overall width does not change with these additional headers

More headers for machine ipmi

---

cmd/helper.go
cmd/machine.go
cmd/printer.go

- Adding filter options
- Show power states
- Generally more condensed output, more useful for operators.

Improvements on `machine issues` cmd.

---

.github/workflows/release.yml

should release this after release tomorrow.

fix upload of release artifacts

---

cmd/machine.go

```
$ metalctl machine ipmi events 032b6000-af8b-11e9-8000-3cecef47702e --last 1
49 | 06/15/2021 | 06:19:12 | Session Audit #0xff |  | Asserted
```

move machine events to machine ipmi events

---

cmd/machine.go

Fixes #128.
Problem is the separate logic for `IssueNonDistinctBMCIP` and `IssueASNUniqueness`, which tries to figure out whether to include a issue or not by only considering the `omit` issues, neglecting `only`.

Fix certain machine issues not properly filtered.

---

cmd/machine.go
go.mod
go.sum

Renames current `machine update` to `machine firmware-update`.

Implement `machine update` command.

---

cmd/machine.go

Use ipmi password from env instead from cli

---

cmd/firewall.go

Solves https://github.com/metal-stack/metalctl/issues/167

bump tailscale version and disable logging

---

cmd/machine.go

You can read this with DEBUG=1 or `machine ipmi` anyway.

Don't hide IPMI password.

---

cmd/audit_test.go
cmd/tableprinters/audit.go

closes #192
below is the new output of the audit ls command.
```
❯ m audit ls
TIME                  REQUEST ID                             COMPONENT   DETAIL                         PATH                                           CODE   USER                       
2023-06-29 08:41:35   01423762-249e-45cc-88f9-326de0929f9d   server      unary                          /api.v1.ClusterService/Create                         anonymous@metal-stack.io     
2023-06-29 08:41:35   01423762-249e-45cc-88f9-326de0929f9d   server      unary                          /api.v1.ClusterService/Create                         anonymous@metal-stack.io     
2023-06-29 08:41:15                                          auth …
```

Revisit audit table printers #192

---

cmd/tableprinters/audit.go

https://github.com/metal-stack/metalctl/pull/197/files/0d2a75bd96279081b6cc6f700e05356940a79fe9#diff-e760f555846aae4d87c9f0cab0ddbf1d1859b351a53b666c4880793b812a2016
Co-author: @Gerrit91

refactor: truncate audit body

---

cmd/switch_test.go
cmd/tableprinters/switch.go

TBD, but I think it's nice to able to see which allocated machine is connected where.

Add wide table for `switch connected-machines`.

---

cmd/tableprinters/machine.go

issues contains all issues
with "--id xxx-xxx" machines contains only the requested machine
fixes https://github.com/metal-stack/metalctl/issues/237

fix: filter out issues from other machines in TablePrinter

---

.github/workflows/docker.yaml
_typos.toml
cmd/size_reservations.go

Ensure no typos are introduced.

Enable typos check

---

cmd/root.go

References: https://github.com/metal-stack/metal-api/pull/594

Support ECDSA Public ssh keys

---

Makefile
go.mod
go.sum

close #287 
References:
- https://github.com/metal-stack/updater/pull/15

use sha512 in updater to fix md5 checksum mismatch errors
