- cmd/network.go
- cmd/printer.go
Resolves #16 
Sample output:
```
10.65.184.11    hostname mismatch               shoot--pz9cj...5cf6676c5-7m8zx  9f83861b-09b9-4a6c-9a19-adb91fd918b1    2c83b020-aa03-4535-8978-6676b0491584    ephemeral       machine:0930a400-6a63-11e9-8000-ac1f6b7b779e
10.65.184.13    autoassigned, but no tags       shoot--pz9cj...5cf6676c5-6pfpl  9f83861b-09b9-4a6c-9a19-adb91fd918b1    2c83b020-aa03-4535-8978-6676b0491584    ephemeral                                                   
10.65.184.15    bound to unallocated machine    shoot--pz9cj...5cf6676c5-2tgtc  9f83861b-09b9-4a6c-9a19-adb91fd918b1    2c83b020-aa03-4535-8978-6676b0491584    ephemeral       machine:bbbe3200-6a76-11e9-8000-ac1f6b7bece4
185.153.67.35   metallb ip without tags         metallb-52ae1                   internet-fel-wps101 …
```
> add metalctl network ip issues command

- cmd/machine.go
fixes https://github.com/metal-stack/metal-api/issues/61 for `metalctl machine ls`
```
$ metalctl machine ls --mac asdf
ID                      LAST EVENT      WHEN    AGE     HOSTNAME        PROJECT SIZE    IMAGE   PARTITION 
$ metalctl machine ls --mac "00:04:00:11:11:01"
ID                                                      LAST EVENT      WHEN    AGE     HOSTNAME        PROJECT SIZE            IMAGE   PARTITION 
e0ab02d2-27cd-5a5e-8efc-080ba80cf258                    Waiting         49s                                     v1-small-x86            vagrant
```
```
$ metalctl machine ipmi --mac asdf
ID              IP      MAC     BOARD PART NUMBER       BIOS VERSION    BMC VERSION     SIZE    PARTITION 
$metalctl machine ipmi --mac "00:04:00:11:11:01"
ID …
```
> fix --mac filter for machine ls

- cmd/machine.go
- cmd/root.go
Since there are stronger ssh keys to protect a ssh connection, please add ed25519 as one of the defaults.
> Add support for ed25519 ssh keys

- cmd/root.go
- go.mod
- go.sum
Use go-homedir instead of viper's $HOME mechanism. References fi-ts/cloudctl#10.
> Fix config file lookup on Windows in home directory.

- cmd/network.go
- cmd/partition.go
- cmd/printer.go
- cmd/project.go
- cmd/size.go
- go.mod
- go.sum
Currently, we just swallow unexpected errors and continue in the code. This leads to odd error messages in the masterdata creation as described in #49.
Requires https://github.com/metal-stack/metal-api/pull/113 in order to work.
> Fixing error handling in apply commands

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
```
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
> Fix deprecated Github Actions steps.

- .gitignore
- cmd/printer.go
- cmd/root.go
- cmd/version.go
Solves https://github.com/metal-stack/metalctl/issues/80
`metalctl` behavior is now more similar to `kubectl`. `metalctl version` prints both server and client versions:
```
client: 1.1, go1.16.5
server:
builddate: "2021-03-29T11:30:07Z"
gitsha1: e843d254
name: metal-api
revision: tags/v0.14.1-0-ge843d25
version: v0.14.1
```
`--version` flag is removed.
One thing that concerns me is that we detailer always prints new line at the end of output(noticeable in `version` and `health` commands output). Is there a reason for that or we can simply remove it?
> version command prints client and server version

- cmd/printer.go
- cmd/version.go
While implementing `version` cmd for cloudctl, i realized that server connection error handled badly -- if we fail to connect to server,  only error is printed. Fixed that, now if there's no connection, we get output like that:
```
client: 1.1, go1.16.5
Error: failed to get server info: Get "http://localhost:8080/metal/v1/version": dial tcp 127.0.0.1:8080: connect: connection refused
```
cc @majst01 
P.S. also returned new line for JSON printer, looks like it missing it by default(unlike YAML one).
> version: always print client version

- cmd/context.go
- cmd/login.go
- cmd/machine.go
- cmd/root.go
- cmd/whoami.go
- crush/main.go
References https://github.com/fi-ts/cloudctl/pull/105.
```BREAKING_CHANGE
The --kubeConfig parameter was renamed to --kubeconfig in order to align with kubectl.
```
> Rename to `--kubeconfig`, better output on context switch.

- cmd/output/printer.go
Before:
```
$ metalctl switch ls -o wide
ID                      PARTITION       RACK                    MODE            LAST SYNC       SYNC DURATION   LAST SYNC ERROR 
fel-wps101-leaf01       fel-wps101      fel-wps101-rack01       operational     14s             1.432s                          
```
With PR:
```
$ metalctl switch ls -o wide
ID                      PARTITION       RACK                    MODE            LAST SYNC       SYNC DURATION   LAST SYNC ERROR                                                    
fel-wps101-leaf01       fel-wps101      fel-wps101-rack01       operational     20s             1.432s          2h 23m ago: could not apply                                       
switch config: reloading                                          
failed failed …
```
> always show last sync error in metalctl switch ls

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
```
On 2022-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name. We strongly advise updating your GitHub Action YAML from: uses: 'google-github-actions/setup-gcloud@master' to: uses: 'google-github-actions/setup-gcloud@v0' While not recommended, you can still pin to the "master" branch by setting the environment variable "SETUP_GCLOUD_I_UNDERSTAND_USING_MASTER_WILL_BREAK_MY_WORKFLOW_ON_2022_04_05=1". However, on 2022-04-05 when the branch is renamed, all your workflows will begin failing with an obtuse and difficult to diagnose error message. For more …
```
> fix gcloud action

- cmd/health.go
Health returns an error when the API is unhealthy. metalctl should still show the payload of the result though.
> Don't error when unhealthy.

- cmd/firewall.go
- cmd/ssh.go
Without this the following error occurs if target node has a ipv6 address:
```
Error: machine console error:failed to connect to proxy at address :1055: socks connect tcp: address fd7a:115c:a1e0::2:22: too many colons in address
```
But still, connection does not work because the route to the destination is not there:
```
/ # tailscale status                                                                                                                                                                                                                                                             
fd7a:115c:a1e0::3 badile-w2s2wqff      00000000-0000-0000-0000-000000000001 linux   - …
```
> At least pass correct ipv6 notation if required

- cmd/common_test.go
- cmd/image_test.go
- cmd/tableprinters/image.go
Somehow when using viper in the tableprinters there are side-effects on other tests being run. Resetting viper before every test fixes it.
> Fix image single result test not being able to run individually.

- pkg/api/issues.go
- pkg/api/issues_test.go
This helps us to detect machines that are in this state before the FSM was introduced.
> Detect FailedMachineReclaim machine issue before new FSM was introduced.

- cmd/switch.go
- cmd/switch_test.go
- cmd/tableprinters/printer.go
- cmd/tableprinters/switch.go
- cmd/tableprinters/switch_test.go
- docs/metalctl_switch_connected-machines.md
Since more than a year I need to generate some output that correlates the machine product serials with the switch ports. 
Therefore, I though it might be useful to add this command such that I can throw away my fork which contains a hackier version of this implementation.
> Add `switch connected-machines` command.

- Makefile
References https://github.com/fi-ts/cloudctl/pull/259.
> For build date use Go-compatible RFC3339 date format, fixes `update check`

- cmd/machine_test.go
- cmd/tableprinters/machine.go
- go.mod
- go.sum
- pkg/api/issues.go
- pkg/api/issues_test.go
TODO:
Current output:
```
m ms ipmi --id 00000000-0000-0000-0000-ac1f6bd390a6 -o wide
ID                                     STATUS   POWER      AGE      IP              MAC                 BOARD PART NUMBER   CHASSIS SERIAL    PRODUCT SERIAL     BIOS VERSION   BMC VERSION   SIZE           PARTITION   RACK             
00000000-0000-0000-0000-ac1f6bd390a6            ON 137 W   3m 35s   10.1.1.16:623   ac:1f:6b:35:5b:07   X11DPT-B            C217BAH23AE0090   A328789X9101143A   3.4            1.73          c1-large-x86   fra-equ01   fra-equ01-rack01 
```
> show ipmi last updated

- cmd/partition_test.go
- cmd/size.go
- cmd/size_test.go
- cmd/sorters/size.go
- cmd/tableprinters/partition.go
- cmd/tableprinters/printer.go
- cmd/tableprinters/size.go
- docs/metalctl_size_reservations.md
- docs/metalctl_size_reservations_check.md
- docs/metalctl_size_reservations_list.md
- go.mod
- go.sum
References https://github.com/metal-stack/metal-api/pull/484.
> Add size reservations cmds and add reservations to partition capacity.

- cmd/common_test.go
- cmd/firewall.go
- cmd/machine.go
- cmd/ssh.go
- cmd/tableprinters/machine.go
- docs/metalctl_machine_console.md
- go.mod
- go.sum
References https://github.com/metal-stack/metal-console/pull/50.
> Allow machine console connection with admin flag.

- go.mod
- go.sum
closes #253 
With this metalctl will error out if a unknown version is given:
```
$ metalctl update do --version v0.17.0
Error: no release for given desired version:"v0.17.0"
```
> Update updater to prevent update to unavailable versions

- cmd/filesystemlayout.go
- cmd/firewall.go
- cmd/ip.go
- cmd/machine.go
- cmd/network.go
- cmd/partition.go
- cmd/partition_test.go
- cmd/project.go
- cmd/size.go
- cmd/size_reservations.go
- cmd/sizeimageconstraint.go
- cmd/switch.go
- cmd/tenant.go
- docs/metalctl_partition_capacity.md
- go.mod
- go.sum
References https://github.com/metal-stack/metal-api/pull/588.
> Update to metal-go v0.39.2.

- cmd/tableprinters/switch.go
- go.mod
- go.sum
support display of the bgp state of connected machines
```
ID                                           NIC NAME                              IDENTIFIER     PARTITION   RACK        SIZE           HOSTNAME   PRODUCT SERIAL
leaf01                                                                                            mini-lab    test-rack
├─╴e0ab02d2-27cd-5a5e-8efc-080ba80cf258      Ethernet0 (BGP:Established(23m48s))   fortyGigE0/0   mini-lab    test-rack   v1-small-x86   test
└─╴2294c949-88f6-5390-8154-fa53d93a3313      Ethernet4 (BGP:Established(23m48s))   fortyGigE0/4   mini-lab    test-rack   v1-small-x86   fw
leaf02                                                                                            mini-lab    test-rack
├─╴e0ab02d2-27cd-5a5e-8efc-080ba80cf258      Ethernet0 …
```
> feat: add support for printing bgp state of connected machines

- README.md
- cmd/root.go
- pkg/api/context.go
As of now, using the metalctl is only possible for admins, but not for viewers or editors.
This adds an optional setting to the config to fit the auth type of the hmac. Default is admin to keep backwards compatibility
> feat: add support for non-Admin HMACs

- cmd/root.go
If not given, this will rely on the default server behavior.
**Alternatively:** make this hmac type mandatory in the config and make this a breaking change.
> fix: bug which required optional hmac type

- cmd/switch_test.go
- cmd/tableprinters/switch.go
- cmd/tableprinters/tenant.go
- cmd/tenant_test.go
- Puts chassis serial to switch connected machines such that it is possible to see which machines are sitting in the same chassis
- Remove labels and annotations from tenants because these can be pretty big (e.g. for metalstack.cloud)
> Small improvements for switch and tenants table.
